				<div class="clear"></div>
			</div>
		</div>
	<div class="clear"></div>
	<div id="footer" style="display: none;">
		<a href="http://support.sharingtime.com/" title="Support">Support</a> | 
		<a href="http://sharingtime.com/about/" title="About">About</a> | 
		<a href="http://sharingtime.com/privacy/" title="Safe">How We Keep Your Data Safe</a> | 
		<a href="http://sharingtime.com/privacy/security/" title="Privacy and Security">Privacy & Security</a> | 
		<a href="http://sharingtime.com/privacy/terms/" title="Terms of Use">Terms of Use</a>
	</div>
<!-- Do not remove the copyright notice unless you have purchased a Commercial License from admintasia.com -->
	<div id="copyright" style="padding-top:15px;">
		&copy; <?=date("Y")?> SharingTime
	</div>
</body>
</html>