<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>SharingTime - Real-time Genealogical Collaboration</title>
	<link rel="shortcut icon" type="image/x-icon" href="http://dev.sharingtime.com/favicon.ico">	
	<script type="text/javascript" src="http://dev.sharingtime.com/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="http://dev.sharingtime.com/js/ui/ui.core.js"></script>
	<script type="text/javascript" src="http://dev.sharingtime.com/js/ui/ui.draggable.js"></script>
	<script type="text/javascript" src="http://dev.sharingtime.com/js/ui/ui.dialog.js"></script>
	<script type="text/javascript" src="http://dev.sharingtime.com/js/ui/effects.core.js"></script>
	<script type="text/javascript" src="http://dev.sharingtime.com/js/ui/effects.highlight.js"></script>
	
		<script type="text/javascript" src="http://dev.sharingtime.com/js/custom.js"></script>

	<link href="http://dev.sharingtime.com/css/ui/ui.base.css" rel="stylesheet" media="all" />
	<link href="http://dev.sharingtime.com/css/ui.css" rel="stylesheet" title="style" media="all" />
	<link href="http://dev.sharingtime.com/css/table_jui.css" rel="stylesheet" title="style" media="all" />	

	<!--[if IE 6]>
	<link href="http://dev.sharingtime.com/css/ie6.css" rel="stylesheet" media="all" />
	
	<script src="http://dev.sharingtime.com/js/pngfix.js"></script>
	<script>
	  /* Fix IE6 Transparent PNG */
	  DD_belatedPNG.fix('.logo, ul#dashboard-buttons li a, .response-msg, #search-bar input');

	</script>
	<![endif]-->
</head>
<body id="sidebar-left" class="layout75">
	<div id="page_wrapper">
		<div id="page-header">
			<div id="page-header-wrapper" class="fixed">

				<div id="top">
					<a href="/dashboard/" class="logo" title="Sharingtime">Sharingtime</a>
					<div class="welcome">
											
						<span class="note">Welcome, <a href="#" title="Welcome, Simon">Simon</a></span>
						<a class="btn ui-state-default ui-corner-all" href="/account/logout">
							<span class="ui-icon ui-icon-power"></span>

							Logout
						</a>						
					</div>
				</div>
				<ul id="navigation">
					<li><a href="/dashboard/">Overview</a></li>				
				</ul>
				<div id="search-bar">
				</div>
			</div>
		</div>
